# Docker Compose
# elasticache-retail-leaderboard-demo
version: "3"
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - redis
  app:
    build: ./app
    ports:
      - "8081:8080"
    depends_on:
      - backend
      - redis
